name: Project CD

on:
  push:
    branches:
      - main
  
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push tranngobichdu/toeic-learning-website-be:v1

      - name: Push Docker Image
        run: docker push tranngobichdu/toeic-learning-website:v1

      - name: SSH into the server and deploy Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 103.169.34.149
          username: ${{ secrets.DOCKER_USERNAME_HOST }}
          password: ${{ secrets.DOCKER_PASSWORD_HOST }}
          script: |
            cd ~/projects/Toeic-Learning-Website
            git pull origin main
            docker compose down -v
            docker compose up --build -d  
