name: Project CD

on:
  push:
    branches:
    - main

permissions: write-all

jobs:
  build-push-fe:
    name: Build and Push FE Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build FE Docker Image
      run: docker build -t tranngobichdu/toeic-learning-website:v1 -f .deploy/fe/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push FE Docker Image
      run: docker push tranngobichdu/toeic-learning-website:v1

  build-push-be:
    name: Build and Push BE Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build BE Docker Image
      run: docker build -t tranngobichdu/toeic-learning-website-be:v1 -f .deploy/be/Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push BE Docker Image
      run: docker push tranngobichdu/toeic-learning-website-be:v1
